spring.application.name=common-lib

server.port=8085

# Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/microservice?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=manager
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver