server:
  port: 9090

spring:
  application:
    name: API-GATEWAY

  cloud:
    gateway:
      server:
        webflux:
          routes:

            - id: AUTH-SERVICE
              uri: http://localhost:8083
              predicates:
                - Path=/auth/**

            - id: EMPLOYEE-SERVICE
              uri: lb://EMPLOYEE
              predicates:
                - Path=/employees/**
              filters:
                - AuthFilter
                - name : CircuitBreaker
                  args:
                    name : EMPLOYEE-SERVICE
                    fallbackUri: forward:/employeeFallback

            - id: ADDRESS-SERVICE
              uri: lb://ADDRESS
              predicates:
                - Path=/addresses/**
              filters:
                - AuthFilter
                - name : CircuitBreaker
                  args:
                    name: ADDRESS-SERVICE
                    fallbackUri: forward:/addressFallback

eureka:
  instance:
    prefer-ip-address: true

  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/


resilience4j:
  circuitbreaker:
    instances:
      EMPLOYEE-SERVICE:
        timeoutDuration: 5s

      ADDRESS-SERVICE:
        timeoutDuration: 5s

  circuitbreakers:
      EMPLOYEE-SERVICE:
        slidingWindowType: COUNT_BASED
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        slidingWindowSize: 5
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 6s
        automaticTransitionFromOpenToHalfOpenEnabled: true
        permittedNumberOfCallsInHalfOpenState: 3

      ADDRESS-SERVICE:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        slidingWindowSize: 5
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 6s
        automaticTransitionFromOpenToHalfOpenEnabled: true
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowType: COUNT_BASED

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,circuitbreakers

  health:
    circuitbreakers:
      enabled: true